export type TMember = {
  EmpCode: string
  FullName: string
  Dept: string
  Cphone: string
  Sex: string
  QT: string
  DirLab: number
  Pass: string
  Addr: string
  AWard: string
  ADistrict: string
  ACity: string
  LongAddress: string
  Email: string
  Position: string
  Title: string
  RegCode: string
  Lday: number
  Ltype: number
  Loff: number
  C1006PK: string
  C1001PK: string
  F40B: string
  F40A: string
  StartDate: string
  DateKey: number
  AllowLeaveHalfDay: boolean
};

export type TMemberProfile = {
  Gender: string
  Datebirth: string
  Identify: string
  Cellphone: string
  StartingDate: string
  DateOfContract: string
  PersonalTaxCode: string
  BHXH: string
  BHYT: string
  STK: string
  NameBank: string
  Img: string
  CountryPermanentPk: string
  ProvincePermanentPk: string
  WardPermanentPk: string
  AddressPermanent: string
  AddressPermanentSecondLanguage: string
  CountryTemporaryPk: string
  ProvinceTemporaryPk: string
  WardTemporaryPk: string
  AddressTemporary: string
  AddressTemporarySecondLanguage: string
  CountryHomeTownPk: string
  ProvinceHomeTownPk: string
  WardHomeTownPk: string
  AddressHomeTown: string
  AddressHomeTownSecondLanguage: string
}
